---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build + test + exec
    image: haskell:8.6.3
    commands:
      - stack test --fast
      - stack exec correct-fizz-buzz-exe
    when:
      event:
        - pull_request

---
kind: signature
hmac: 33b0af49ba881f509e01bbd9e2a1b09b2ae468088063695fdca846fb2a455b30
