---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build + test + exec
    image: haskell:8.6.3
    commands:
      - stack test --fast
      - stack exec correct-fizz-buzz-exe
    when:
      event:
        - pull_request
        - push

---
kind: signature
hmac: e4c0d2c9531a3d75147319b7cba2b713d0eba6553cbd4182e801499dba09b4eb
